version: "3.4"

services:
  nightscout:
    image: "nightscout/cgm-remote-monitor:14.2.5"    
    environment:
      API_SECRET: "${API_SECRET:-123456789abc}"
      MONGO_CONNECTION: 'mongodb://${MONGODB_USERNAME:-nightscout}:${MONGODB_PASSWORD:-secret}@database/nightscout?retryWrites=true&w=majority&authSource=admin'
      MONGO_COLLECTION: 'entries'
      INSECURE_USE_HTTP: "true"
      SECURE_HSTS_HEADER: "false"
      ENABLE: "basal bwp careportal iob cob rawbg treatmentnotify boluscalc profile food ar2"
      SHOW_PLUGINS: "careportal"
      TREATMENTS_AUTH: "off"
      PORT: 1337
      TIME_FORMAT: "24"
      DISPLAY_UNITS: "mmol"
      WAIT_HOSTS: "database:27017"
    depends_on:
      - database
    expose:
      - "1337"
    ports:
      - "5001:1337"

  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: nightscout
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:-nightscout}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-secret}
      AUTH: 'true'
    expose:
      - 27017
      - 27018
      - 27019